site_name: "Patchestry: MLIR-based binary patching framework"
repo_url: https://github.com/lifting-bits/patchestry
nav:
  - Introduction: README.md
  - Getting Started:
    - Build & Run: GettingStarted/build.md
    - Ghidra Integration: GettingStarted/ghidra.md
    - How to contribute: CONTRIBUTING.md
  - Benchmarks:
  - About:
    - 'License': 'statement.md'

theme:
  name: material
  language: en
  favicon: assets/img/favicon.ico

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: pink

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: pink

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: pink

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/slack
      link: https://slack.empirehacking.nyc/

  copyright: Copyright &copy; 2024 Trail of Bits
